server:
  port: 8080
spring:
  application:
    name: client
eureka:
  instance:
    prefer-ip-address: false
  client:
    #表示是否将自己注册到Eureka Server
    register-with-eureka: true
    #表示是否从Eureka Server获取注册的服务信息
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.com:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true


